### PR TITLE
Fix caret synchronization on in block-wise RGA

### LINKED ISSUE #228: Cursor synchronisation is off on RGA blocks
We use the RGA to lookup cursor positions.

After the transition to block-wise RGA we forgot to account for this in cursor synch. Thus, the cursor are now in the "beginning" of the block instead of its actual place

### PR DESCRIPTION
**Pull request by rehnarama**
Fixes #228

### CODE REVIEW

File: packages/frontend/src/functions/CursorWidget/CursorWidget.ts [hunk 1]
```diff
@@ -84,8 +118,8 @@ class CursorWidget implements monaco.editor.IContentWidget {
    * @param id  Where in the document (currently open in the file given in the
```
Comment (AdamInersjo) [inline packages/frontend/src/functions/CursorWidget/CursorWidget.ts]: Update documentation of method to match new parameter `cursor`
