### PR TITLE
Fix faulty removal and code clean up

### LINKED ISSUE #177: Remove Socket on both signout & disconnect in project has faulty code
See: 
https://github.com/rehnarama/MALTE/blob/3e0750f1d47c2d65ea7ee2adcc6ef291f4c1b32c/packages/backend/src/functions/Project.ts#L161-L165

We check if index exists and remove that socket. However, [`findIndex`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex) returns -1 when not found which is a "truthy" value, thus entering the if-case. Negative start values in [`splice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) removes from the end instead. 

Thus, if not found we will remove the last user in the list. So, if your first sign out, and then disconnect, you will remove a user who hasn't signed out or disconnected themselves! Worse, it will probably throw an exception if you are the last one online and both sign out and disconnect.

### PR DESCRIPTION
**Pull request by noler**
NB! Only executed this in my mind. Please check if you agree with my fix. Fixes #177

### CODE REVIEW

File: packages/backend/src/functions/Project.ts [hunk 1]
```diff
@@ -168,23 +168,22 @@ export default class Project {
     }
   }
 
-  private async removeSocket(socket: SocketIO.Socket): Promise<void> {
+  private async removeSocket(socket: SocketIO.Socket): Promise<boolean> {
     const index = this.sockets.findIndex(s => s.id === socket.id);
-    if (index) {
+    if (index !== -1) {
       this.sockets.splice(index, 1);
+      if (this.cursorMap[socket.id]) delete this.cursorMap[socket.id];
```
Comment (rehnarama) [inline packages/backend/src/functions/Project.ts]: After we update the cursor map we should broadcast it again, i.e.
```
       this.broadcastCursorList(); 
```

File: packages/backend/src/functions/Project.ts [hunk 2]
```diff
@@ -168,23 +168,22 @@ export default class Project {
...
-    const filesToClose: File[] = [];
-    for (const file of this.files) {
-      const canCloseFile = file.leave(socket);
-      if (canCloseFile) filesToClose.push(file);
+      const filesToClose: File[] = [];
+      for (const file of this.files) {
+        const canCloseFile = file.leave(socket);
+        if (canCloseFile) filesToClose.push(file);
+      }
+      this.closeFiles(filesToClose);
```
Comment (rehnarama) [inline packages/backend/src/functions/Project.ts]: Should either `await` here, or remove `async` from function declaration.

File: packages/backend/src/functions/Project.ts [hunk 3]
```diff
@@ -168,23 +168,25 @@ export default class Project {
     }
   }
 
-  private async removeSocket(socket: SocketIO.Socket): Promise<void> {
+  private removeSocket(socket: SocketIO.Socket): Promise<boolean> {
```
Comment (rehnarama) [inline packages/backend/src/functions/Project.ts]: When we are not async anymore we don't return a promise, just a boolean
```suggestion
  private removeSocket(socket: SocketIO.Socket): boolean {
```

**Comment by rehnarama** [comment]
Looks good! Solve conflict then merge
