### PR TITLE
Add persistent sessions to fix bug of client being stuck on disconnect

### LINKED ISSUE #193: After backend restart, client is stuck until log out/log in
Right now, if the backend is restarted, and the client reconnects, they won't be authenticated anymore. Thus, no actions can be performed.

The only way to solve this is to refresh the page/sign out so that you can authenticate once again.

This is a quite bad user experience. We should either
- Persist user ids in database: this way we can seamlessly reconnect without losing any state (probably the nicest way!)
- Redirect to login screen when losing connection so that user can press authenticate button again (not as nice but easiest)

### PR DESCRIPTION
**Pull request by rehnarama**
Fixes #193 

Now, when a client disconnects (either server or client loosing connection) you will be tossed onto login screen until you have reconnected.

When reconnection occurs, a new authentication attempt will be made which will throw them back into the frontend

### CODE REVIEW

File: packages/backend/src/functions/session/Session.ts [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+    userId
+  });
+
+  return res.deletedCount;
+}
+
+export async function updateSessionTimestamp(userId: string): Promise<void> {
+  const collection = getCollection();
+
+  await collection.updateMany(
```
Comment (noler) [inline packages/backend/src/functions/session/Session.ts]: Why are you not using `updateOne`?

File: packages/backend/src/functions/session/Session.ts [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+
+  return sessions;
+}
+
+export async function removeSession(
+  userId: string
+): Promise<number | undefined> {
+  const collection = getCollection();
+
+  const res = await collection.deleteMany({
```
Comment (noler) [inline packages/backend/src/functions/session/Session.ts]: Why are you not using `deleteOne`?

File: packages/backend/src/functions/session/Session.ts (hunk 1 above)
Comment (rehnarama) [reply packages/backend/src/functions/session/Session.ts]: Because I think there's a possibility that multiple sessions with same user id can be created, e.g. if someone refreshes the page on "/oauth/github/callback", which would probably insert a duplicate sessions.

HOWEVER, a better idea would be to make userId a unique index to prevent this problem and ensure there is one session per userId and one only. Good catch 👍

File: packages/backend/src/functions/session/Session.ts (hunk 2 above)
Comment (rehnarama) [reply packages/backend/src/functions/session/Session.ts]: See comment above

File: packages/backend/src/functions/oauth/GitHub.ts [hunk 3]
```diff
@@ -136,6 +137,19 @@ export default class GitHub {
       return res.sendStatus(401);
     }
 
+    try {
+      // Register this session in db
+      await addSession(userId, user.id);
+    } catch (e) {
```
Comment (noler) [inline packages/backend/src/functions/oauth/GitHub.ts]: Can this be avoided? One should avoid programming normal program logic with exceptions.

File: packages/backend/src/functions/session/Session.ts [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+    .getDb()
+    .collection<Session>("sessions");
+
+  collection.createIndex(
+    { lastSeen: 1 },
+    {
+      expireAfterSeconds: SESSION_EXPIRATION_SECONDS
+    }
+  );
+  collection.createIndex({ userId: 1 }, { unique: true });
```
Comment (noler) [inline packages/backend/src/functions/session/Session.ts]: 👍

File: packages/backend/src/functions/oauth/GitHub.ts (hunk 3 above)
Comment (rehnarama) [reply packages/backend/src/functions/oauth/GitHub.ts]: I wouldn't say it's logic with exceptions, it's an exception from the database and the mongo driver exposes this as a javascript error. There's really no other way other than querying the database twice which would be an anti-pattern; we can rely on mongo ensuring the uniqueness property and should use this functionality.

We could move the try/catch into the addSession functionality and simply re-throw the exception if it is another exception than 11000. Maybe that'd be better to avoid leaking internal details of the session?

Comment (noler) [reply packages/backend/src/functions/oauth/GitHub.ts]: Sounds reasonable
