### PR TITLE
Fix "Model already exists" and tabs not loading content on re-opening

### LINKED ISSUE #176: "Model already exists" in multi-user collaborative session
To reproduce:
* Create two files, _a.js_ & _b.js_
* Open _a.js_
* Close _a.js_, leading to no open tabs
* Open _a.js_ (will not contain any content - part of bug)
* Open _b.js_ (will not contain any content - part of bug)
* Now the error will appear!

### PR DESCRIPTION
**Pull request by AdamInersjo**
Fixes #176

### CODE REVIEW

File: packages/frontend/src/functions/Editor.ts [hunk 1]
```diff
@@ -58,6 +49,25 @@ export default class Editor {
...
+        const movement: CursorMovement = {
+          path: this.activeFile.path,
+          id: rgaPosition
+        };
+        socket.emit("cursor/move", movement);
+      }
+    });
+  }
+
+  public changeEditorInstance(newEditor: editorType.ICodeEditor) {
```
Comment (rehnarama) [inline packages/frontend/src/functions/Editor.ts]: Should probably be removed since it isn't used anymore, right?

File: packages/frontend/src/functions/File.ts [hunk 2]
```diff
@@ -25,10 +25,17 @@ export default class File {
...
+  private editor: editorType.ICodeEditor;
 
   private applyingRemote = false;
 
-  constructor(path: string, content: RGAJSON, model: editorType.ITextModel) {
+  constructor(
+    path: string,
+    content: RGAJSON,
+    model: editorType.ITextModel,
+    editor: editorType.ICodeEditor
```
Comment (rehnarama) [inline packages/frontend/src/functions/File.ts]: We never use  "editor". Any reason why pass it in?

Comment (AdamInersjo) [reply packages/frontend/src/functions/File.ts]: Nice catch! That was done for testing purpouses earlier!
